version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAZURESTAGINGProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQA_GitRuntimeAZURESTAGINGProject
  gitUsername: siqagituser
  gitBranch: main
